### ISSUE TITLE
Catch JSON parse errors?

### ISSUE THREAD

**Issue by IceDragon200** [tenderlove/heap-analyzer#3]
I uploaded a dump to the app, with incomplete line causing the JSON parse to silently fail.
A nice addition would be to catch these errors and display a notification: 
`Sorry, but there seems to be a problem with your dump`

**Comment by yosiat** [comment]
Hi,
What do we want to do on parse error?
1. Stop the processing and show the parse errors, and re-submit after fix?
2. Continue and show the errors?

BTW, I think this is problem with ObjectSpace dumping, it takes tame to flush and dump_all finishes before flushing all data.

**Comment by IceDragon200** [comment]
@yosiat Preferably 1, 2 would open the door for more errors (missing entries leading to a dead end when referenced)

**Comment by yosiat** [comment]
Ok, I will submit a pull request for this later

**Comment by yosiat** [comment]
Hi @IceDragon200,
This is fixed and updated (at tenderlove.github.io/heap-analyzer/), can you check it's ok?

**Comment by IceDragon200** [comment]
@yosia Just tried it, and its ok

Nah, its awesome, I won't be staring at the screen wondering if my connection is slow or it failed anymore
